name: git-bszakaly # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Git # 79 char long summary
description: |
  Git

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  git:
    source: https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.39.3.tar.xz
    plugin: autotools
    build-packages: [make, libssl-dev, libcurl4-openssl-dev, libexpat-dev, tcl, tk, gettext, zlib1g-dev, perl-modules, liberror-perl, libauthen-sasl-perl, libemail-valid-perl, libio-socket-ssl-perl, libnet-smtp-ssl-perl]
    stage-packages: [make, libssl-dev, libcurl4-openssl-dev, libexpat-dev, tcl, tk, gettext, zlib1g-dev, perl-modules, liberror-perl, libauthen-sasl-perl, libemail-valid-perl, libio-socket-ssl-perl, libnet-smtp-ssl-perl]