name: git-bszakaly
base: core22
version: '2.39.3'
summary: Git
description: |
  Source https://github.com/bszakaly/git-snap

grade: stable
confinement: strict

apps:
  git:
    command: usr/local/bin/git
    environment:
      GIT_EXEC_PATH: ${SNAP}/usr/local/libexec/git-core
      GIT_TEMPLATE_DIR: ${SNAP}/usr/local/share/git-core/templates
    plugs:
      - network
      - home
      - ssh-keys

parts:
  git:
    source: https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.39.3.tar.xz
    plugin: autotools
    build-packages: [make, libssl-dev, libcurl4-openssl-dev, libexpat-dev, tcl, tk, gettext, zlib1g-dev, perl-modules, liberror-perl, libauthen-sasl-perl, libemail-valid-perl, libio-socket-ssl-perl, libnet-smtp-ssl-perl]
    stage-packages: [curl]